### PR TITLE
changed the magnify glass icon in the header to plain text

### PR DESCRIPTION
**Pull request by arianahabas**
The header had two 'search' options and there was nothing that distinguished the 'map search' from a regular search. To improve user experience, the magnify glass icon in the header was changed to plain text, it now says 'Map View'.

### CODE REVIEW

**Review by saramatic — DISMISSED** [review]
Thanks for updating the magnify glass icon so it isn't confusing. I am still researching the mapboxGLmap info to see why that isn't linking up

**Comment by tinomen** [comment]
Why are we making this change? Is it to fix the UX of the search icon? Lets edit the main description to be more clear about why this change is happening.

**Review by tinomen — CHANGES_REQUESTED** [review]
There are some unused components in the import that should be removed

**Review by saramatic — DISMISSED** [review]
Thanks for updating the changes that Jake suggested

**Review by tinomen — DISMISSED** [review]
Nice job on the description changes. Very clear what the motivation is and what you've done. 

PR is tiny, which is always nice to review ;)

**Pull request closed without merging**
